Algoritmo "variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Criar algoritmo
// Autor(a)    : Cintia
// Data atual  : 04/11/2022
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

          primeiroNome, segundoNome, cidade, endereço: caractere
          idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo